// Generated by scripts/release.mjs — do not edit manually.
import Foundation

extension FeedbackClient {
    /// The current semantic version of the CupThread Apple SDK.
    public static let sdkVersion = "0.1.0"

    /// The SDK identifier reported in submission metadata and request headers.
    public static let sdkName = "cupthread-apple"

    /// The formatted SDK descriptor combining name and version (e.g. `cupthread-apple/0.1.0`).
    public static var sdkIdentifier: String {
        "\(sdkName)/\(sdkVersion)"
    }
}
