import Foundation

/// Persists a stable anonymous user token across app launches.
/// Used to track vote state and own pending requests without requiring authentication.
///
/// The token is a plain UUID stored in `UserDefaults.standard`; it never
/// carries personal data and can be regenerated by deleting the app. Pass it
/// wherever the SDK asks for a `userToken`:
///
/// ```swift
/// FeatureRequestsView(client: client, userToken: UserTokenStore.shared.token)
/// ```
public final class UserTokenStore: @unchecked Sendable {
    /// The shared store, backed by `UserDefaults.standard`.
    public static let shared = UserTokenStore()

    /// The default key used in `UserDefaults` to store the anonymous token.
    static let defaultKey = "com.cupthread.featureRequestUserToken"

    private static let processLock = NSLock()

    private let userDefaults: UserDefaults
    private let key: String

    /// Initializes a token store with the specified defaults suite and storage key.
    /// Internal to allow unit tests to pass isolated `UserDefaults` and keys.
    init(userDefaults: UserDefaults = .standard, key: String = UserTokenStore.defaultKey) {
        self.userDefaults = userDefaults
        self.key = key
    }

    /// Returns the existing token, or generates and persists a new UUID on first access.
    ///
    /// Synchronized across threads and instances via double-checked locking so concurrent
    /// first accesses always resolve and persist the same identity.
    public var token: String {
        if let existing = userDefaults.string(forKey: key), !existing.isEmpty {
            return existing
        }

        Self.processLock.lock()
        defer { Self.processLock.unlock() }

        if let existing = userDefaults.string(forKey: key), !existing.isEmpty {
            return existing
        }

        let new = UUID().uuidString
        userDefaults.set(new, forKey: key)
        return new
    }
}
