import Foundation

/// Persists a stable anonymous user token across app launches.
/// Used to track vote state and own pending requests without requiring authentication.
///
/// The token is a plain UUID stored in `UserDefaults.standard`; it never
/// carries personal data and can be regenerated by deleting the app. Pass it
/// wherever the SDK asks for a `userToken`:
///
/// ```swift
/// FeatureRequestsView(client: client, userToken: UserTokenStore.shared.token)
/// ```
public final class UserTokenStore: @unchecked Sendable {
    /// The shared store, backed by `UserDefaults.standard`.
    public static let shared = UserTokenStore()

    private let key = "com.cupthread.featureRequestUserToken"

    private init() {}

    /// Returns the existing token, or generates and persists a new UUID on first access.
    public var token: String {
        if let existing = UserDefaults.standard.string(forKey: key) {
            return existing
        }
        let new = UUID().uuidString
        UserDefaults.standard.set(new, forKey: key)
        return new
    }
}
