import Testing
@testable import CupThreadFeedback

/// Pins `UserAttributesSigner.canonicalNumber` and the signed MRR vectors to the
/// server's JavaScript canonicalization (ECMA-262 `toFixed(2)` on the exact binary
/// double + trailing-zero strip, DATA-03). Pure functions — no client state.
@Suite("UserAttributesCanonicalNumber")
struct UserAttributesCanonicalNumberTests {
    @Test func canonicalNumberMatchesServerToFixedSemantics() {
        // Spec examples (DATA-03)
        #expect(UserAttributesSigner.canonicalNumber(10.125) == "10.13")
        #expect(UserAttributesSigner.canonicalNumber(1200.005) == "1200.01")
        #expect(UserAttributesSigner.canonicalNumber(99.995) == "100")
        // Exact-binary rounding basis: the double for these literals sits below the
        // decimal value, so no carry happens even though the decimal ends in 5.
        #expect(UserAttributesSigner.canonicalNumber(9.995) == "9.99")
        #expect(UserAttributesSigner.canonicalNumber(2.675) == "2.67")
        #expect(UserAttributesSigner.canonicalNumber(0.025) == "0.03")
        #expect(UserAttributesSigner.canonicalNumber(1.005) == "1")
        #expect(UserAttributesSigner.canonicalNumber(4.995) == "5")
        #expect(UserAttributesSigner.canonicalNumber(12.555) == "12.55")
        #expect(UserAttributesSigner.canonicalNumber(12.545) == "12.54")
        #expect(UserAttributesSigner.canonicalNumber(1.145) == "1.15")
        #expect(UserAttributesSigner.canonicalNumber(1.135) == "1.14")
        // Dyadic exact ties round away from zero, matching Node's observable
        // toFixed behavior on both signs.
        #expect(UserAttributesSigner.canonicalNumber(1.125) == "1.13")
        #expect(UserAttributesSigner.canonicalNumber(0.125) == "0.13")
        #expect(UserAttributesSigner.canonicalNumber(0.625) == "0.63")
        #expect(UserAttributesSigner.canonicalNumber(12.125) == "12.13")
        #expect(UserAttributesSigner.canonicalNumber(8.875) == "8.88")
        #expect(UserAttributesSigner.canonicalNumber(-1.125) == "-1.13")
        #expect(UserAttributesSigner.canonicalNumber(-0.625) == "-0.63")
        // A negative value rounding below one cent keeps its sign ("-" + "0");
        // -0.005 itself sits above the decimal literal and carries to "-0.01".
        #expect(UserAttributesSigner.canonicalNumber(-0.004) == "-0")
        #expect(UserAttributesSigner.canonicalNumber(-0.005) == "-0.01")
        // Negative zero normalizes like JS ToString.
        #expect(UserAttributesSigner.canonicalNumber(-0.0) == "0")
        // Existing renderings keep passing.
        #expect(UserAttributesSigner.canonicalNumber(1200.0) == "1200")
        #expect(UserAttributesSigner.canonicalNumber(99.5) == "99.5")
        #expect(UserAttributesSigner.canonicalNumber(12.34) == "12.34")
        #expect(UserAttributesSigner.canonicalNumber(0.0) == "0")
    }

    @Test func canonicalNumberMatchesNodeOnPinnedBitPatterns() {
        // Regression table generated by differential-testing the implementation
        // against Node's `v.toFixed(2)` + trailing-zero strip over 374k inputs
        // (structured half-cents/dyadic ties/random bit patterns); each row pins
        // the exact IEEE 754 bit pattern so the tested double is unambiguous.
        let table: [(UInt64, String)] = [
            (0x4024400000000000, "10.13"), (0x4092c0051eb851ec, "1200.01"),
            (0x4023fd70a3d70a3d, "9.99"), (0x4005666666666666, "2.67"),
            (0x3ff2000000000000, "1.13"), (0x3fc0000000000000, "0.13"),
            (0x3fe4000000000000, "0.63"), (0x4028400000000000, "12.13"),
            (0x3f9999999999999a, "0.03"), (0x40291c28f5c28f5c, "12.55"),
            (0x4029170a3d70a3d7, "12.54"), (0x3ff228f5c28f5c29, "1.14"),
            (0x3ff251eb851eb852, "1.15"), (0x4058ffae147ae148, "100"),
            (0x4013fae147ae147b, "5"), (0x4021c00000000000, "8.88"),
            (0xbff2000000000000, "-1.13"), (0x8000000000000000, "0"),
            (0x0000000000000000, "0"), (0x4092c00000000000, "1200"),
            (0x4058e00000000000, "99.5"), (0x4028ae147ae147ae, "12.34"),
            (0x412e848000000000, "1000000"), (0x3fb999999999999a, "0.1"),
            (0x3fa999999999999a, "0.05"), (0x4029000000000000, "12.5"),
            (0x0000000000000001, "0"), (0x3ff0147ae147ae14, "1"),
            (0x3ff03d70a3d70a3d, "1.01"), (0x3ff0666666666666, "1.02"),
            (0xc029170a3d70a3d7, "-12.54"), (0xbf747ae147ae147b, "-0.01"),
            (0xbf70624dd2f1a9fc, "-0"), (0xc415af1d78b58c40, "-100000000000000000000"),
            (0x4415af1d78b58c40, "100000000000000000000"),
            (0x432ff973cafa8000, "4500000000000000"), (0x4363fbe85edc9000, "45000000000000000"),
            (0x4383fbe85edc9000, "180000000000000000"), (0x43e158e460913d00, "10000000000000000000"),
            (0xc3e158e460913d00, "-10000000000000000000"), (0x4340000000000000, "9007199254740992"),
            (0xc201b1a2e451fd16, "-9499335818.25"), (0xc411b52e8e66757f, "-81662544548391272448"),
            (0xbfc0000000000000, "-0.13"), (0xbfd8000000000000, "-0.38"),
            (0xbfec000000000000, "-0.88"), (0x402bc00000000000, "13.88"),
            (0xc02bc00000000000, "-13.88"), (0x3fefae147ae147ae, "0.99"),
            (0x4048f9999999999a, "49.95"), (0x4058fccccccccccd, "99.95"),
            (0xbff4000000000000, "-1.25"), (0xbf847ae147ae147b, "-0.01"),
            (0x6f6e423ed667ff15, "5.734532462417211e+228"), (0x31e0506f668055ab, "0"),
            (0xf416421cad6d5fc0, "-1.5936297138127255e+251"),
            (0xeb0604bb88e20655, "-3.5345529666779085e+207"),
            (0x855f583d698af719, "-0"), (0xe7481ae8266904b7, "-3.3562655444807736e+189"),
            (0x8defadfd7a0e1b7e, "-0"), (0x3dd3229ff18318c8, "0"),
            (0xe31e4668944d2cf9, "-2.856420947725064e+169"),
            (0xcf15152ba271a8e0, "-9.312475354670871e+72"),
            (0x6e25b921bb2173b1, "3.926178430269941e+222"),
            (0xf838927b3c9cdb6c, "-1.2981355150248724e+271"),
            (0xdfa5f77e050ab9da, "-5.752464613116391e+152"),
            (0x26e97a9bd8c79a29, "0"), (0xe2a92e2b536fbf5d, "-1.8560486223551816e+167"),
            (0xff7ecf54070b1763, "-1.3522144142076257e+306"),
            (0xe88d79737c36b98d, "-4.303209080157528e+195"),
            (0xe69cd07a6f2d17be, "-1.9589639282478716e+186")
        ]
        for (bits, expected) in table {
            #expect(
                UserAttributesSigner.canonicalNumber(Double(bitPattern: bits)) == expected,
                "bit pattern 0x\(String(bits, radix: 16)) should canonicalize to \(expected)"
            )
        }
    }

    private struct MRRVector {
        let mrr: Double
        let mrrCanonical: String
        let expectedSignature: String
    }

    @Test func signaturePinsKnownServerMRRVectors() {
        // End-to-end vectors computed against the server's JS canonicalization
        // (Node: toFixed(2) + trailing-zero strip, then HMAC-SHA256), so any
        // regression in canonical formatting — not just the rounding mode — breaks
        // here. 10.125 is an exact dyadic tie ("10.13"); 9.995 exercises the exact
        // binary rounding basis ("9.99", the stored double is 9.994999…).
        let vectors = [
            MRRVector(
                mrr: 10.125,
                mrrCanonical: "10.13",
                expectedSignature: "4a6bf11e015e3d46565dbda9ffe9eeb42ed53a053a3c45d05cef1655648194d2"
            ),
            MRRVector(
                mrr: 9.995,
                mrrCanonical: "9.99",
                expectedSignature: "4e3471d68755f2eff52cc08a857192c777b03fff2596864c5f5b8e895e3f2bff"
            )
        ]
        let secret = "test_secret_key"
        for vector in vectors {
            let canonical = UserAttributesSigner.canonicalString(
                for: .init(
                    appKey: "app_demo",
                    userToken: "tok_123",
                    isPaying: true,
                    plan: "pro",
                    mrr: vector.mrr,
                    currency: "USD",
                    timestamp: 1773600000
                )
            )
            #expect(canonical.contains(vector.mrrCanonical))
            #expect(
                UserAttributesSigner.signature(for: canonical, secret: secret) == vector.expectedSignature,
                "HMAC vector mismatch for mrr \(vector.mrr) (canonical \(vector.mrrCanonical))"
            )
        }
    }
}
