#!/usr/bin/env node
import { spawnSync } from "node:child_process";
import { createHash } from "node:crypto";
import { existsSync, mkdtempSync, mkdirSync, readdirSync, readFileSync, realpathSync, rmSync, statSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import path from "node:path";
import { fileURLToPath } from "node:url";
import readline from "node:readline/promises";

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const R2_BUCKET = process.env.R2_BUCKET || "cupthread-sdks";
const CDN_BASE = process.env.CDN_BASE || "https://cdn.cupthread.com";

export const RELEASE_BRANCH = "main";
// The 0.1.0 CDN object predates this release pipeline and its exact source
// provenance is unverifiable (issues #11 and #55). It must never be repointed
// or overwritten, so the version itself is unreleasable.
export const RESERVED_VERSIONS = {
  "0.1.0": "the CDN object CupThreadFeedback-0.1.0.xcframework.zip predates this release pipeline and its exact source provenance is unverifiable (issues #11 and #55); publish 0.1.1 or later instead"
};
const VERSION_FILE = "Sources/CupThreadFeedback/SDKVersion.swift";

// --- Exported for ReleasePreflightTests: pure version helpers -------------

export function isSemver(version) {
  return /^\d+\.\d+\.\d+$/.test(version);
}

export function compareSemver(a, b) {
  const pa = a.split(".").map(Number);
  const pb = b.split(".").map(Number);
  if (pa.length !== 3 || pb.length !== 3 || pa.some(Number.isNaN) || pb.some(Number.isNaN)) {
    throw new Error(`Invalid semver: ${JSON.stringify(a)}, ${JSON.stringify(b)}`);
  }
  for (let i = 0; i < 3; i++) {
    if (pa[i] !== pb[i]) return pa[i] < pb[i] ? -1 : 1;
  }
  return 0;
}

// Greatest tag of the form vX.Y.Z, or null when the repository has none yet.
export function greatestVersionTag(tagNames) {
  const tags = tagNames.filter((name) => /^v\d+\.\d+\.\d+$/.test(name));
  if (tags.length === 0) return null;
  return tags.sort((a, b) => compareSemver(a.slice(1), b.slice(1)))[tags.length - 1];
}

export function artifactFilename(version) {
  return `CupThreadFeedback-${version}.xcframework.zip`;
}

export function sdkVersionFileContent(version) {
  return `// Generated by scripts/release.mjs — do not edit manually.
import Foundation

extension FeedbackClient {
    /// The current semantic version of the CupThread Apple SDK.
    public static let sdkVersion = "${version}"

    /// The SDK identifier reported in submission metadata and request headers.
    public static let sdkName = "cupthread-apple"

    /// The formatted SDK descriptor combining name and version (e.g. \`cupthread-apple/0.1.0\`).
    public static var sdkIdentifier: String {
        "\\(sdkName)/\\(sdkVersion)"
    }
}
`;
}

export function syncSDKVersion(version) {
  const versionFile = path.join(ROOT, VERSION_FILE);
  const content = sdkVersionFileContent(version);
  if (existsSync(versionFile) && readFileSync(versionFile, "utf8") === content) {
    return false;
  }
  writeFileSync(versionFile, content, "utf8");
  return true;
}

// --- Exported for ReleasePreflightTests: pure preflight decisions ----------
//
// evaluateReleaseReadiness turns probed repository/remote state into pass/fail
// decisions without touching git, gh, or the network, so `swift test` can pin
// every rule. `artifactSha256` is null during the pre-build preflight and set
// during the post-build re-evaluation; several rules only fire once the
// freshly built artifact's checksum is known.

export function evaluateReleaseReadiness(facts) {
  const errors = [];
  const warnings = [];
  const completed = { tag: false, githubRelease: false, cdnObject: false };
  const version = facts.version;
  const tag = `v${version}`;
  const artifact = artifactFilename(version);

  if (facts.version && !isSemver(facts.version)) {
    errors.push(`Version ${facts.version} is not plain semver (expected X.Y.Z).`);
  }

  if (facts.branch !== RELEASE_BRANCH) {
    errors.push(`Releases must be cut from ${RELEASE_BRANCH} (found: ${facts.branch || "none"}). Switch with: git switch ${RELEASE_BRANCH}`);
  }

  if (isToleratedPendingVersionState(facts)) {
    warnings.push(`Working tree carries the generated ${VERSION_FILE} from a previous release attempt; it will be committed for this release.`);
  } else if (facts.statusLines && facts.statusLines.length > 0) {
    errors.push(`Working tree is not clean — commit or stash everything before releasing. git status --porcelain:\n    ${facts.statusLines.join("\n    ")}`);
  }

  if (facts.fetchError) {
    errors.push(`Could not fetch origin to compare ${RELEASE_BRANCH} ancestry: ${facts.fetchError}`);
  } else if (facts.headSha && facts.originMainSha && facts.originMainSha !== facts.headSha && facts.originMainIsAncestorOfHead === false) {
    errors.push(`Local ${RELEASE_BRANCH} (${shortSha(facts.headSha)}) is behind or diverged from origin/${RELEASE_BRANCH} (${shortSha(facts.originMainSha)}). Fast-forward with: git merge --ff-only origin/${RELEASE_BRANCH}`);
  }

  if (RESERVED_VERSIONS[version]) {
    errors.push(`Version ${version} is reserved and must not be republished: ${RESERVED_VERSIONS[version]}`);
  }

  const latestTag = facts.latestTag;
  if (latestTag && latestTag !== tag) {
    const latestVersion = latestTag.slice(1);
    if (!isSemver(latestVersion)) {
      warnings.push(`Latest version tag ${latestTag} is not plain semver; skipping the version-monotonicity check.`);
    } else if (compareSemver(version, latestVersion) <= 0) {
      errors.push(`Version ${version} is not greater than the latest release tag ${latestTag}. Pick a higher version.`);
    }
  }

  if (facts.remoteTagProbeError) {
    errors.push(`Could not list remote tags to check for an existing ${tag}: ${facts.remoteTagProbeError}`);
  } else {
    if (facts.localTagCommitSha && facts.localTagCommitSha !== facts.headSha) {
      errors.push(`Tag ${tag} already exists locally at ${shortSha(facts.localTagCommitSha)} but HEAD is ${shortSha(facts.headSha)}. Move to that commit or delete the tag with: git tag -d ${tag}`);
    }
    if (facts.remoteTagCommitSha && facts.remoteTagCommitSha !== facts.headSha) {
      errors.push(`Tag ${tag} already exists on origin at ${shortSha(facts.remoteTagCommitSha)} but HEAD is ${shortSha(facts.headSha)} — refusing to move a remote tag.`);
    }
    if (facts.localTagCommitSha && facts.localTagCommitSha === facts.headSha) {
      if (facts.remoteTagCommitSha === facts.headSha) {
        completed.tag = true;
      } else {
        warnings.push(`Tag ${tag} exists locally at HEAD but has not been pushed; it will be pushed during publication.`);
      }
    }
  }

  const release = facts.githubRelease;
  if (release) {
    if (release.isDraft) {
      warnings.push(`A draft GitHub release for ${tag} already exists; its assets will be replaced with the freshly built artifact.`);
    } else if (facts.artifactSha256) {
      if (!release.assetNames.includes(artifact)) {
        errors.push(`GitHub release ${tag} is already published but has no ${artifact} asset — treating ${version} as releasable would leave an ambiguous state. Publish a new version instead.`);
      } else if (release.bodySha256 && release.bodySha256 !== facts.artifactSha256) {
        errors.push(`Published GitHub release ${tag} advertises checksum ${release.bodySha256} but this build is ${facts.artifactSha256} — mismatched artifact, refusing to continue.`);
      } else {
        completed.githubRelease = true;
      }
    } else {
      warnings.push(`GitHub release ${tag} is already published; the freshly built artifact will be checked against it before anything is uploaded.`);
    }
  }

  const cdn = facts.cdnObject;
  if (cdn && cdn.exists) {
    if (!facts.artifactSha256) {
      warnings.push(`CDN object ${artifact} already exists; its checksum will be verified against the freshly built artifact before any upload.`);
    } else if (cdn.sha256 === facts.artifactSha256) {
      completed.cdnObject = true;
    } else if (release && !release.isDraft) {
      errors.push(`CDN object ${artifact} exists with checksum ${cdn.sha256} but this build is ${facts.artifactSha256}, and the GitHub release is already published — refusing to mutate a published artifact.`);
    } else {
      warnings.push(`CDN object ${artifact} exists with a different checksum (${cdn.sha256}); the release is unpublished, so publication will overwrite it with the verified build.`);
    }
  }

  return { errors, warnings, completed };
}

// A dirty tree is fatal — except for exactly one state: the generated
// version file left uncommitted by a previous release attempt of the same
// version. Reruns recognize it instead of forcing a manual checkout.
function isToleratedPendingVersionState(facts) {
  if (facts.versionFilePendingRelease !== true) return false;
  const lines = facts.statusLines || [];
  return lines.length > 0 && lines.every((line) => line.slice(3) === VERSION_FILE);
}

function shortSha(sha) {
  return sha ? sha.slice(0, 12) : "none";
}

// --- Probing (impure): turn git/gh/CDN state into preflight facts ----------

function probe(cmd, args, opts = {}) {
  const result = spawnSync(cmd, args, {
    cwd: opts.cwd ?? ROOT,
    stdio: ["ignore", "pipe", "pipe"],
    encoding: "utf8",
    maxBuffer: 64 * 1024 * 1024
  });
  return {
    ok: result.status === 0 && !result.error,
    status: result.status,
    stdout: (result.stdout || "").trim(),
    stderr: (result.stderr || "").trim()
  };
}

function requireCommands(commands) {
  const missing = commands.filter((cmd) => !probe("sh", ["-c", `command -v ${cmd}`]).ok);
  if (missing.length > 0) {
    fail(`Missing required tools: ${missing.join(", ")} — install them before releasing.`);
  }
}

function requireGhAuth() {
  if (!probe("gh", ["auth", "status"]).ok) {
    fail("gh is not authenticated — run `gh auth login` before releasing.");
  }
}

function gitStatusLines() {
  return probe("git", ["status", "--porcelain"]).stdout.split("\n").filter(Boolean);
}

function gitHeadSha() {
  const out = probe("git", ["rev-parse", "HEAD"]);
  return out.ok ? out.stdout : null;
}

function gitBranch() {
  const out = probe("git", ["rev-parse", "--abbrev-ref", "HEAD"]);
  return out.ok ? out.stdout : null;
}

function localTagCommitSha(tag) {
  const out = probe("git", ["rev-parse", "-q", "--verify", `${tag}^{commit}`]);
  return out.ok ? out.stdout : null;
}

// For annotated tags ls-remote lists both the tag object and the peeled
// `^{}` commit; lightweight tags list the commit directly. Either way the
// returned sha is the commit the tag names.
function remoteTagCommitSha(tag) {
  const out = probe("git", ["ls-remote", "origin", `refs/tags/${tag}`, `refs/tags/${tag}^{}`]);
  if (!out.ok) return { sha: null, error: out.stderr || `git ls-remote exited ${out.status}` };
  const lines = out.stdout.split("\n").filter(Boolean);
  const peeled = lines.find((line) => line.endsWith(`refs/tags/${tag}^{}`));
  const plain = lines.find((line) => line.endsWith(`refs/tags/${tag}`));
  return { sha: peeled ? peeled.split("\t")[0] : (plain ? plain.split("\t")[0] : null), error: null };
}

function githubReleaseInfo(tag) {
  const out = probe("gh", ["release", "view", tag, "--json", "isDraft,assets,body"]);
  if (!out.ok) return null; // "release not found" — anything else is caught by requireGhAuth
  try {
    const parsed = JSON.parse(out.stdout);
    const body = typeof parsed.body === "string" ? parsed.body : "";
    const checksumIndex = body.indexOf("checksum ");
    const bodySha256 = checksumIndex >= 0 ? (body.slice(checksumIndex + "checksum ".length).match(/^[0-9a-f]{64}/) || [null])[0] : null;
    return {
      isDraft: parsed.isDraft === true,
      assetNames: (parsed.assets || []).map((asset) => asset.name),
      bodySha256
    };
  } catch {
    return null;
  }
}

// Probe the published CDN object (if any). A random query parameter busts
// CDN caches so the check observes the object itself, not a cached copy.
function cdnObjectInfo(filename) {
  const url = `${CDN_BASE}/sdks/apple/${filename}?probe=${process.pid}-${Date.now()}`;
  const dir = mkdtempSync(path.join(tmpdir(), "cupthread-cdn-probe-"));
  try {
    const file = path.join(dir, "object.bin");
    const out = probe("curl", ["-fsSL", "-o", file, "--max-time", "120", url]);
    if (!out.ok) return { exists: false };
    return { exists: true, sha256: sha256(file) };
  } finally {
    rmSync(dir, { recursive: true, force: true });
  }
}

function collectPreflightFacts(version, planUpload) {
  const facts = {
    version,
    branch: gitBranch(),
    statusLines: gitStatusLines(),
    versionFilePendingRelease: false,
    headSha: gitHeadSha(),
    originMainSha: null,
    originMainIsAncestorOfHead: false,
    fetchError: null,
    latestTag: null,
    localTagCommitSha: null,
    remoteTagCommitSha: null,
    remoteTagProbeError: null,
    githubRelease: null,
    cdnObject: null
  };

  const versionFile = path.join(ROOT, VERSION_FILE);
  facts.versionFilePendingRelease = existsSync(versionFile)
    && readFileSync(versionFile, "utf8") === sdkVersionFileContent(version);

  const fetched = probe("git", ["fetch", "origin", RELEASE_BRANCH, "--quiet"]);
  if (fetched.ok) {
    const origin = probe("git", ["rev-parse", `origin/${RELEASE_BRANCH}`]);
    facts.originMainSha = origin.ok ? origin.stdout : null;
    facts.originMainIsAncestorOfHead = probe("git", ["merge-base", "--is-ancestor", `origin/${RELEASE_BRANCH}`, "HEAD"]).ok;
  } else {
    facts.fetchError = fetched.stderr || `git fetch exited ${fetched.status}`;
  }

  facts.latestTag = greatestVersionTag(
    probe("git", ["tag", "--list", "v*"]).stdout.split("\n").filter(Boolean)
  );
  facts.localTagCommitSha = localTagCommitSha(`v${version}`);
  const remote = remoteTagCommitSha(`v${version}`);
  facts.remoteTagCommitSha = remote.sha;
  facts.remoteTagProbeError = remote.error;
  facts.githubRelease = githubReleaseInfo(`v${version}`);
  if (planUpload) {
    facts.cdnObject = cdnObjectInfo(artifactFilename(version));
  }
  return facts;
}

function runPreflight(version, planUpload) {
  requireCommands(["git", "gh", "swift", "xcodebuild", "curl", "npx", "libtool", "lipo", "nm", "ditto"]);
  requireGhAuth();
  const { facts, collectErrors } = collectPreflightFactsWithErrors(version, planUpload);
  const decision = evaluateReleaseReadiness(facts);
  for (const warning of decision.warnings) console.log(`  ⚠︎ ${warning}`);
  const errors = [...collectErrors, ...decision.errors];
  if (errors.length > 0) {
    console.error("✗ Release preflight failed:");
    for (const error of errors) console.error(`  - ${error}`);
    console.error("  See docs/release-runbook.md for remedies.");
    process.exit(1);
  }
  console.log("  preflight OK");
  return facts;
}

function collectPreflightFactsWithErrors(version, planUpload) {
  const collectErrors = [];
  const facts = collectPreflightFacts(version, planUpload);
  if (!facts.headSha) collectErrors.push("Could not resolve HEAD — is this a git checkout?");
  return { facts, collectErrors };
}

// --- Publication helpers ---------------------------------------------------

// run() throws instead of exiting so publication steps can wrap failures
// with recovery instructions; main()'s catch converts throws to exit 1.
function run(cmd, args, opts = {}) {
  console.log(`  $ ${cmd} ${args.join(" ")}`);
  const result = spawnSync(cmd, args, {
    cwd: opts.cwd ?? ROOT,
    stdio: opts.capture ? ["ignore", "pipe", "inherit"] : "inherit",
    encoding: "utf8",
    // `nm` on a slice archive emits megabytes of symbols; the 1MB default
    // maxBuffer would SIGTERM the child and lose the output.
    maxBuffer: 64 * 1024 * 1024
  });
  if (result.error) throw new Error(`Command failed: ${cmd} ${args.join(" ")} (${result.error.message})`);
  if (result.status !== 0) throw new Error(`Command failed (${result.status}): ${cmd} ${args.join(" ")}`);
  return result.stdout;
}

function withRecovery(step, recovery, fn) {
  try {
    return fn();
  } catch (error) {
    console.error(`✗ ${step}: ${error.message}`);
    console.error(`  RECOVERY: ${recovery}`);
    process.exit(1);
  }
}

function fail(message) {
  console.error(`✗ ${message}`);
  process.exit(1);
}

function sha256(file) {
  const hash = createHash("sha256");
  hash.update(readFileSync(file));
  return hash.digest("hex");
}

function parseArgs(argv) {
  const args = { dryRun: false, skipTests: false, yes: false, version: null, skipUpload: false, syncVersionOnly: false };
  for (let i = 0; i < argv.length; i++) {
    const arg = argv[i];
    if (arg === "--version") args.version = argv[++i];
    else if (arg === "--dry-run") args.dryRun = true;
    else if (arg === "--skip-tests") args.skipTests = true;
    else if (arg === "--skip-upload") args.skipUpload = true;
    else if (arg === "--yes") args.yes = true;
    else if (arg === "--sync-version-only") args.syncVersionOnly = true;
    else fail(`Unknown argument: ${arg}`);
  }
  if (!args.version || !isSemver(args.version)) {
    fail("--version must be specified as semver, e.g. --version 0.1.0");
  }
  return args;
}

function humanSize(bytes) {
  if (bytes >= 1024 * 1024) return `${(bytes / (1024 * 1024)).toFixed(1)} MB`;
  return `${Math.max(1, Math.round(bytes / 1024))} KB`;
}

const APPLE_SLICES = [
  { name: "ios", destination: "generic/platform=iOS", minimumOSVersion: "17.0" },
  { name: "ios-simulator", destination: "generic/platform=iOS Simulator", minimumOSVersion: "17.0" },
  { name: "macos", destination: "generic/platform=macOS", minimumOSVersion: "14.0" },
  { name: "visionos", destination: "generic/platform=visionOS", minimumOSVersion: "1.0" },
  { name: "visionos-simulator", destination: "generic/platform=visionOS Simulator", minimumOSVersion: "1.0" },
  { name: "tvos", destination: "generic/platform=tvOS", minimumOSVersion: "17.0" },
  { name: "tvos-simulator", destination: "generic/platform=tvOS Simulator", minimumOSVersion: "17.0" }
];
const RESOURCE_BUNDLE_NAME = "CupThreadFeedback_CupThreadFeedback.bundle";
// Privacy manifest shipped at the root of every static framework slice (and
// inside the SPM resource bundle for source-package consumers). Xcode 15+
// aggregates it into host apps; a slice without one would leave host apps to
// declare the SDK's required-reason API usage by hand (ITMS-91053).
const PRIVACY_MANIFEST_NAME = "PrivacyInfo.xcprivacy";
const PRIVACY_MANIFEST_SOURCE = path.join(ROOT, "Sources", "CupThreadFeedback", PRIVACY_MANIFEST_NAME);
const CONSUMER_APP_KEY = "app_static_linkage_probe";
// Matches the archs each slice must ship (mirrors AGENTS.md's platform matrix).
const SLICE_ARCHS = {
  "ios": ["arm64"],
  "ios-simulator": ["arm64", "x86_64"],
  "macos": ["arm64", "x86_64"],
  "visionos": ["arm64"],
  "visionos-simulator": ["arm64", "x86_64"],
  "tvos": ["arm64"],
  "tvos-simulator": ["arm64", "x86_64"]
};

// The SPM product is static (see Package.swift), so archives install a bare
// Mach-O object instead of a dylib framework. Each XCFramework slice is a
// static .framework: the libtool'd archive plus the generated ObjC header and
// the swiftmodule (with library-evolution .swiftinterface files) so both Xcode
// and SwiftPM `.binaryTarget` consumers can import and statically link it.
function findArchivedObject(archiveDir, sliceName) {
  const products = path.join(archiveDir, "Products");
  const found = [];
  const visit = (dir) => {
    for (const entry of readdirSync(dir, { withFileTypes: true })) {
      const full = path.join(dir, entry.name);
      if (entry.isDirectory()) visit(full);
      else if (entry.name === "CupThreadFeedback.o") found.push(full);
    }
  };
  if (existsSync(products)) visit(products);
  if (found.length !== 1) {
    throw new Error(`Expected exactly one CupThreadFeedback.o under ${products} for ${sliceName}, found ${found.length}`);
  }
  return found[0];
}

function findGeneratedHeader(derivedData, sliceName) {
  const intermediates = path.join(
    derivedData, "Build", "Intermediates.noindex", "ArchiveIntermediates",
    "CupThreadFeedback", "IntermediateBuildFilesPath"
  );
  const generatedDirs = readdirSync(intermediates, { withFileTypes: true })
    .filter((e) => e.isDirectory() && e.name.startsWith("GeneratedModuleMaps"))
    .map((e) => path.join(intermediates, e.name));
  const header = generatedDirs
    .map((dir) => path.join(dir, "CupThreadFeedback-Swift.h"))
    .find((p) => existsSync(p));
  if (!header) {
    throw new Error(`No CupThreadFeedback-Swift.h under GeneratedModuleMaps* for ${sliceName}`);
  }
  return header;
}

function findSwiftmodule(derivedData, sliceName) {
  const buildProducts = path.join(
    derivedData, "Build", "Intermediates.noindex", "ArchiveIntermediates",
    "CupThreadFeedback", "BuildProductsPath"
  );
  const found = [];
  const visit = (dir) => {
    for (const entry of readdirSync(dir, { withFileTypes: true })) {
      const full = path.join(dir, entry.name);
      if (!entry.isDirectory()) continue;
      if (entry.name === "CupThreadFeedback.swiftmodule") found.push(full);
      else visit(full);
    }
  };
  if (existsSync(buildProducts)) visit(buildProducts);
  if (found.length !== 1) {
    throw new Error(`Expected exactly one CupThreadFeedback.swiftmodule under ${buildProducts} for ${sliceName}, found ${found.length}`);
  }
  return found[0];
}

// xcodebuild installs only the object into the archive Products; the SPM
// resource bundle stays behind in the archive intermediates, so it must be
// copied out explicitly for consumers whose host apps carry the bundle.
function findBuiltResourceBundle(derivedData, sliceName) {
  const uninstalled = path.join(
    derivedData, "Build", "Intermediates.noindex", "ArchiveIntermediates",
    "CupThreadFeedback", "IntermediateBuildFilesPath", "UninstalledProducts"
  );
  const found = [];
  const visit = (dir) => {
    for (const entry of readdirSync(dir, { withFileTypes: true })) {
      if (!entry.isDirectory()) continue;
      const full = path.join(dir, entry.name);
      if (entry.name === RESOURCE_BUNDLE_NAME) found.push(full);
      else visit(full);
    }
  };
  if (existsSync(uninstalled)) visit(uninstalled);
  if (found.length !== 1) {
    throw new Error(`Expected exactly one ${RESOURCE_BUNDLE_NAME} under ${uninstalled} for ${sliceName}, found ${found.length}`);
  }
  return found[0];
}

function frameworkInfoPlist(version, slice) {
  return `<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>CFBundleDevelopmentRegion</key><string>en</string>
  <key>CFBundleExecutable</key><string>CupThreadFeedback</string>
  <key>CFBundleIdentifier</key><string>com.cupthread.CupThreadFeedback</string>
  <key>CFBundleInfoDictionaryVersion</key><string>6.0</string>
  <key>CFBundleName</key><string>CupThreadFeedback</string>
  <key>CFBundlePackageType</key><string>FMWK</string>
  <key>CFBundleShortVersionString</key><string>${version}</string>
  <key>CFBundleVersion</key><string>${version}</string>
  <key>MinimumOSVersion</key><string>${slice.minimumOSVersion}</string>
</dict>
</plist>
`;
}

function stageStaticFramework(slice, archiveDir, derivedData, work, version) {
  const fw = path.join(work, "static", slice.name, "CupThreadFeedback.framework");
  const isMacOS = slice.name === "macos";
  const binaryDir = isMacOS ? path.join(fw, "Versions", "A") : fw;
  mkdirSync(path.join(binaryDir, "Headers"), { recursive: true });
  mkdirSync(path.join(binaryDir, "Modules"), { recursive: true });
  if (isMacOS) {
    mkdirSync(path.join(binaryDir, "Resources"), { recursive: true });
    writeFileSync(path.join(binaryDir, "Resources", "Info.plist"), frameworkInfoPlist(version, slice));
  } else {
    writeFileSync(path.join(fw, "Info.plist"), frameworkInfoPlist(version, slice));
  }

  // The archived object is already fat where the platform is universal
  // (macOS/simulator slices ship arm64 + x86_64), so a single libtool -static
  // pass wraps it into the slice's static archive.
  const object = findArchivedObject(archiveDir, slice.name);
  run("libtool", ["-static", "-o", path.join(binaryDir, "CupThreadFeedback"), object]);
  run("cp", [findGeneratedHeader(derivedData, slice.name), path.join(binaryDir, "Headers")]);
  run("cp", ["-R", findSwiftmodule(derivedData, slice.name), path.join(binaryDir, "Modules", "CupThreadFeedback.swiftmodule")]);
  run("cp", [PRIVACY_MANIFEST_SOURCE, path.join(binaryDir, PRIVACY_MANIFEST_NAME)]);

  if (isMacOS) {
    run("ln", ["-sfn", "A", path.join(fw, "Versions", "Current")]);
    for (const link of ["CupThreadFeedback", "Headers", "Modules", "Resources"]) {
      run("ln", ["-sfn", path.join("Versions", "Current", link), path.join(fw, link)]);
    }
  }
  return fw;
}

function verifyStaticBinary(framework, expectedArchs) {
  const binary = path.join(framework, "CupThreadFeedback");
  const archs = run("lipo", ["-archs", binary], { capture: true }).trim().split(/\s+/).sort();
  const expected = [...expectedArchs].sort();
  if (archs.join(" ") !== expected.join(" ")) {
    throw new Error(`${framework}: expected static archive archs [${expected.join(", ")}], found [${archs.join(", ")}]`);
  }
  const symbols = run("nm", [binary], { capture: true });
  // Swift word-substitution mangling means literal type names never appear;
  // the module token does, in every symbol the SDK defines.
  if (!symbols.includes("17CupThreadFeedback")) {
    throw new Error(`${framework}: static archive has no CupThreadFeedback symbols — refusing to ship an empty library`);
  }
}

// The privacy manifest must sit at the framework bundle root so Xcode 15+
// aggregates the SDK's required-reason API and collected-data declarations
// into host apps. The spot-checked markers mirror PrivacyManifestTests.swift.
function verifyPrivacyManifest(framework, label) {
  const versioned = path.join(framework, "Versions", "A");
  const base = existsSync(versioned) ? versioned : framework;
  const manifest = path.join(base, PRIVACY_MANIFEST_NAME);
  if (!existsSync(manifest)) {
    throw new Error(`${label} is missing ${PRIVACY_MANIFEST_NAME} at the framework root — host apps would be left to declare the SDK's required-reason API usage by hand`);
  }
  const content = readFileSync(manifest, "utf8");
  for (const marker of [
    "NSPrivacyTracking",
    "NSPrivacyAccessedAPICategoryUserDefaults",
    "CA92.1",
    "NSPrivacyCollectedDataTypeUserID",
    "NSPrivacyCollectedDataTypeOtherUserContent"
  ]) {
    if (!content.includes(marker)) {
      throw new Error(`${label} privacy manifest is missing the ${marker} declaration`);
    }
  }
}

function verifyStaticXCFramework(xcframework) {
  for (const entry of readdirSync(xcframework, { withFileTypes: true })) {
    if (!entry.isDirectory()) continue;
    const framework = path.join(xcframework, entry.name, "CupThreadFeedback.framework");
    if (!existsSync(framework)) {
      throw new Error(`XCFramework slice ${entry.name} has no CupThreadFeedback.framework`);
    }
    // Slice dir names encode their architectures (e.g. ios-arm64,
    // macos-arm64_x86_64, ios-arm64_x86_64-simulator). The underscore inside
    // "x86_64" rules out naive splitting, but the SDK matrix only ships
    // arm64 and x86_64, so substring presence is exact.
    const archs = entry.name.includes("x86_64") ? ["arm64", "x86_64"] : ["arm64"];
    verifyStaticBinary(framework, archs);

    const versioned = path.join(framework, "Versions", "A");
    const base = existsSync(versioned) ? versioned : framework;
    if (!existsSync(path.join(base, "Headers", "CupThreadFeedback-Swift.h"))) {
      throw new Error(`XCFramework slice ${entry.name} is missing Headers/CupThreadFeedback-Swift.h`);
    }
    const swiftmodule = path.join(base, "Modules", "CupThreadFeedback.swiftmodule");
    if (!existsSync(swiftmodule)) {
      throw new Error(`XCFramework slice ${entry.name} is missing Modules/CupThreadFeedback.swiftmodule — Swift consumers could not import the module`);
    }
    verifyPrivacyManifest(framework, `XCFramework slice ${entry.name}`);
    for (const arch of archs) {
      const hasInterface = readdirSync(swiftmodule).some(
        (name) => name.startsWith(`${arch}-apple-`) && name.endsWith(".swiftinterface")
      );
      if (!hasInterface) {
        throw new Error(`XCFramework slice ${entry.name} swiftmodule has no ${arch}-apple-*.swiftinterface`);
      }
    }
  }
}

function verifyResourceBundle(bundle, sourceLprojs) {
  const resourcesDir = [
    path.join(bundle, "Contents", "Resources"),
    bundle
  ].find((p) => existsSync(path.join(p, "en.lproj")));
  if (!resourcesDir) {
    throw new Error(`${RESOURCE_BUNDLE_NAME} has no en.lproj`);
  }
  if (!existsSync(path.join(resourcesDir, "en.lproj", "Localizable.strings"))) {
    throw new Error(`${RESOURCE_BUNDLE_NAME} is missing en.lproj/Localizable.strings`);
  }
  const have = new Set(readdirSync(resourcesDir).filter((n) => n.endsWith(".lproj")));
  const missing = sourceLprojs.filter((lproj) => !have.has(lproj));
  if (missing.length > 0) {
    throw new Error(`${RESOURCE_BUNDLE_NAME} missing localizations: ${missing.join(", ")}`);
  }
}

function installInstructionsMarkdown(version) {
  return `# Installing CupThreadFeedback ${version}

The XCFramework contains **static** libraries: the SDK is linked into your app
binary, so nothing is embedded and no \`CupThreadFeedback\` dylib ships in your
bundle. Static libraries cannot carry resources, so the localized strings
bundle (\`${RESOURCE_BUNDLE_NAME}\`) is included in this folder and must be
added to your app target.

Each framework slice embeds a \`PrivacyInfo.xcprivacy\` manifest at its bundle
root. Xcode 15+ automatically aggregates it into your app's privacy report —
it declares the SDK's \`UserDefaults\` required-reason usage (CA92.1) and the
data types the SDK transmits (anonymous user ID, optional name/email, user
content). No manual action is needed; mirror the declarations in your own
privacy labels if your app reports them.

## License

CupThreadFeedback is released under the MIT license; the \`LICENSE\` file in
this folder carries the full grant text. If your app displays third-party
acknowledgements, include that text with the CupThreadFeedback entry when
your compliance process requires it.

## Xcode

1. Drag \`CupThreadFeedback.xcframework\` into your app target's
   *Frameworks, Libraries, and Embedded Content* (embedding is not needed —
   "Do Not Embed" is correct for a static framework).
2. Drag \`${RESOURCE_BUNDLE_NAME}\` into your target and make sure it appears
   under *Copy Bundle Resources*. Without it, the first localized string
   lookup crashes.

## Swift Package Manager (binary target)

Point \`.binaryTarget\` at this zip, and add the resource bundle to the app
target that presents CupThread surfaces (download this folder from the GitHub
release and add the bundle to *Copy Bundle Resources*).

Source-package consumers get all of this automatically: SwiftPM copies the
resource bundle and links the library statically.
`;
}

async function verifyStaticConsumer(zipPath, work) {
  const consumer = path.join(work, "consumer-probe");
  rmSync(consumer, { recursive: true, force: true });
  mkdirSync(path.join(consumer, "Sources", "ConsumerProbe"), { recursive: true });
  // SwiftPM rejects absolute paths for local binary targets — the probe
  // package sits next to the zip, so a relative path is one `..` away.
  const relativeZip = path.relative(consumer, path.resolve(zipPath));
  writeFileSync(path.join(consumer, "Package.swift"), `// swift-tools-version: 6.0
import PackageDescription

let package = Package(
    name: "ConsumerProbe",
    platforms: [.macOS(.v14)],
    targets: [
        .binaryTarget(name: "CupThreadFeedback", path: "${relativeZip.replace(/"/g, '\\"')}"),
        .executableTarget(name: "ConsumerProbe", dependencies: ["CupThreadFeedback"])
    ]
)
`);
  writeFileSync(path.join(consumer, "Sources", "ConsumerProbe", "main.swift"), `import Foundation
import CupThreadFeedback

let configuration = FeedbackClientConfiguration(
    baseURL: URL(string: "https://api.cupthread.com")!,
    appKey: "${CONSUMER_APP_KEY}"
)
let client = FeedbackClient(configuration: configuration)
print("probe:", client.configuration.appKey, FeedbackPlatform.current)
`);
  console.log("• verifying binary channel with a consumer probe package");
  run("swift", ["build"], { cwd: consumer });
  const probeOutput = run(path.join(consumer, ".build", "debug", "ConsumerProbe"), [], { capture: true, cwd: consumer });
  if (!probeOutput.includes(CONSUMER_APP_KEY)) {
    throw new Error(`Consumer probe printed unexpected output: ${probeOutput.trim()}`);
  }

  const buildDir = path.join(consumer, ".build");
  const visit = (dir, onEntry) => {
    for (const entry of readdirSync(dir, { withFileTypes: true })) {
      const full = path.join(dir, entry.name);
      if (entry.isDirectory()) visit(full, onEntry);
      else onEntry(full);
    }
  };
  visit(buildDir, (file) => {
    if (file.endsWith(".dylib") && path.basename(file).startsWith("libCupThreadFeedback")) {
      throw new Error(`Consumer build produced a CupThreadFeedback dylib: ${file}`);
    }
  });
  const executable = path.join(buildDir, "debug", "ConsumerProbe");
  const loads = run("otool", ["-L", executable], { capture: true });
  if (loads.includes("CupThreadFeedback")) {
    throw new Error(`Consumer binary still loads CupThreadFeedback dynamically:\n${loads}`);
  }
  const symbols = run("nm", [executable], { capture: true });
  if (!symbols.includes("17CupThreadFeedback")) {
    throw new Error("Consumer binary does not statically contain CupThreadFeedback symbols");
  }
  console.log("  consumer probe: module import, static linkage, and runtime OK");
}

function verifyCdnChecksum(filename, expectedSha256) {
  console.log("• verifying the uploaded CDN object's checksum");
  const info = cdnObjectInfo(filename);
  if (!info.exists) {
    fail(`CDN object ${filename} is not reachable right after upload (propagation or cache issue?). The GitHub release is still a draft; check ${CDN_BASE}/sdks/apple/${filename} and rerun — the rerun recognizes the tag and the draft release.`);
  }
  if (info.sha256 !== expectedSha256) {
    fail(`CDN object ${filename} serves checksum ${info.sha256} but the verified build is ${expectedSha256}. The GitHub release is still a draft; overwrite the R2 object and rerun.`);
  }
  console.log(`  sha256:${expectedSha256} verified on CDN`);
}

async function main() {
  const args = parseArgs(process.argv.slice(2));
  const version = args.version;

  if (args.syncVersionOnly) {
    const changed = syncSDKVersion(version);
    console.log(changed ? `✓ Synced SDK version to ${version}` : `✓ SDK version already at ${version}`);
    return;
  }

  if (args.dryRun) {
    console.log("• [dry-run] skipping release preflight — branch, ancestry, tag, release, and CDN collision checks only guard real publications");
  } else {
    console.log("• preflight");
    runPreflight(version, !args.skipUpload);
  }

  if (!args.dryRun && !args.yes) {
    if (!process.stdout.isTTY) fail("Refusing to publish without --yes (or use --dry-run).");
    const rl = readline.createInterface({ input: process.stdin, output: process.stdout });
    const answer = await rl.question(`Release Apple SDK v${version} to ${CDN_BASE} + GitHub? [y/N] `);
    rl.close();
    if (!/^y(es)?$/i.test(answer.trim())) fail("Aborted.");
  }

  console.log(`\n🍎 Building CupThread Apple SDK v${version}`);
  const work = path.join(ROOT, "build/release");
  rmSync(work, { recursive: true, force: true });
  mkdirSync(work, { recursive: true });

  if (!args.dryRun) {
    console.log(`• syncing SDK version to ${version}`);
    if (syncSDKVersion(version)) {
      run("git", ["add", VERSION_FILE]);
      const status = run("git", ["status", "--porcelain", VERSION_FILE], { capture: true });
      if (status && status.trim()) {
        run("git", ["commit", "-m", `chore: bump SDK version to ${version}`]);
      }
    }
  } else {
    console.log(`• [dry-run] would sync SDK version constant to ${version}`);
  }

  if (!args.skipTests) {
    console.log("• swift test");
    run("swift", ["test"], { cwd: ROOT });
  }

  console.log("• archiving platform slices");
  const frameworks = [];
  for (const slice of APPLE_SLICES) {
    const derivedData = path.join(work, "derived-data", slice.name);
    run("xcodebuild", [
      "archive",
      "-scheme", "CupThreadFeedback",
      "-destination", slice.destination,
      "-archivePath", path.join(work, `${slice.name}.xcarchive`),
      "-derivedDataPath", derivedData,
      "SKIP_INSTALL=NO",
      "BUILD_LIBRARY_FOR_DISTRIBUTION=YES",
      "-quiet"
    ], { cwd: ROOT });
    frameworks.push(stageStaticFramework(slice, path.join(work, `${slice.name}.xcarchive`), derivedData, work, version));
  }

  console.log("• verifying static framework slices");
  for (const slice of APPLE_SLICES) {
    const framework = path.join(work, "static", slice.name, "CupThreadFeedback.framework");
    if (!existsSync(framework)) {
      throw new Error(`Missing static framework slice for ${slice.name} at: ${framework}`);
    }
    const binary = path.join(framework, slice.name === "macos"
      ? path.join("Versions", "A", "CupThreadFeedback")
      : "CupThreadFeedback");
    if (!existsSync(binary)) {
      throw new Error(`Missing static binary for ${slice.name} at: ${binary}`);
    }
    verifyStaticBinary(framework, SLICE_ARCHS[slice.name]);
    verifyPrivacyManifest(framework, `Static framework slice ${slice.name}`);
  }

  console.log("• assembling XCFramework");
  const xcframework = path.join(work, "CupThreadFeedback.xcframework");
  run("xcodebuild", ["-create-xcframework", ...frameworks.flatMap((f) => ["-framework", f]), "-output", xcframework]);

  console.log("• verifying static XCFramework slices");
  verifyStaticXCFramework(xcframework);

  console.log("• staging resource bundle");
  const sourceLprojs = readdirSync(path.join(ROOT, "Sources", "CupThreadFeedback", "Resources"))
    .filter((name) => name.endsWith(".lproj"));
  const releaseDir = path.join(work, `CupThreadFeedback-${version}`);
  mkdirSync(releaseDir, { recursive: true });
  run("cp", ["-R", xcframework, path.join(releaseDir, "CupThreadFeedback.xcframework")]);
  run("cp", ["-R", findBuiltResourceBundle(path.join(work, "derived-data", "ios"), "ios"), path.join(releaseDir, RESOURCE_BUNDLE_NAME)]);
  run("cp", [path.join(ROOT, "LICENSE"), path.join(releaseDir, "LICENSE")]);
  writeFileSync(path.join(releaseDir, "INSTALL.md"), installInstructionsMarkdown(version));
  verifyResourceBundle(path.join(releaseDir, RESOURCE_BUNDLE_NAME), sourceLprojs);

  const filename = artifactFilename(version);
  const zipPath = path.join(work, filename);
  run("ditto", ["-c", "-k", "--sequesterRsrc", "--keepParent", releaseDir, zipPath]);

  const artifact = {
    name: "XCFramework (iOS · macOS · visionOS · tvOS, static)",
    filename,
    url: `${CDN_BASE}/sdks/apple/${filename}`,
    size: humanSize(statSync(zipPath).size),
    sha256: sha256(zipPath)
  };
  console.log(`  ${filename}  ${artifact.size}  sha256:${artifact.sha256}`);

  await verifyStaticConsumer(zipPath, work);

  const releaseInfo = {
    sdk: "apple",
    version,
    date: new Date().toISOString().slice(0, 10),
    artifact,
    notes: [
      `CupThread Apple SDK v${version}`,
      "Static-library XCFramework: hosts link the SDK into their own binary (no embedded dylib, dead-code stripping applies).",
      "The zip carries the localized-strings bundle — add it to your app target's Copy Bundle Resources (see INSTALL.md).",
      "Every framework slice ships a PrivacyInfo.xcprivacy manifest (UserDefaults CA92.1 + collected-data types), aggregated automatically by Xcode 15+.",
      "SwiftUI surfaces: roadmap board, What's New, feature requests, feedback composer.",
      "iOS 17+ · macOS 14+ (universal arm64 + x86_64) · visionOS 1.0+ · tvOS 17+.",
      `Binary target with checksum ${artifact.sha256}.`
    ]
  };

  const infoFile = path.join(work, "release-info.json");
  writeFileSync(infoFile, JSON.stringify(releaseInfo, null, 2) + "\n");

  if (args.dryRun) {
    console.log(`\n  [dry-run] Apple SDK v${version} built successfully.`);
    return;
  }

  // Publication order (issue #11): tag the exact build commit → draft GitHub
  // release with the artifact attached → R2 upload → CDN checksum
  // verification → only then publish the draft. Nothing becomes public
  // half-verified, and every stage is safe to rerun.

  console.log("• verifying publication state against the fresh artifact");
  const { facts, collectErrors } = collectPreflightFactsWithErrors(version, !args.skipUpload);
  const decision = evaluateReleaseReadiness({ ...facts, artifactSha256: artifact.sha256 });
  for (const warning of decision.warnings) console.log(`  ⚠︎ ${warning}`);
  if (collectErrors.length > 0 || decision.errors.length > 0) {
    console.error("✗ Publication state check failed:");
    for (const error of [...collectErrors, ...decision.errors]) console.error(`  - ${error}`);
    console.error("  See docs/release-runbook.md for remedies.");
    process.exit(1);
  }

  if (decision.completed.tag && decision.completed.githubRelease && decision.completed.cdnObject) {
    console.log(`\n✓ Apple SDK v${version} is already fully released — tag, GitHub release, and CDN object all match this exact build. Nothing to do.`);
    return;
  }

  const tag = `v${version}`;
  const notes = releaseInfo.notes.map((n) => `- ${n}`).join("\n");

  if (!decision.completed.tag) {
    if (!facts.localTagCommitSha) {
      run("git", ["tag", "-a", tag, "-m", `Release ${tag}`]);
    }
    withRecovery(
      "tag push failed",
      `nothing is published yet (the tag exists locally). Resolve the push, or drop the local tag with \`git tag -d ${tag}\`, then rerun — the rerun recognizes the tag state.`,
      () => run("git", ["push", "origin", tag])
    );
    const pushed = remoteTagCommitSha(tag);
    if (pushed.error || pushed.sha !== facts.headSha) {
      fail(`Tag ${tag} on origin does not point at the release commit ${shortSha(facts.headSha)} after push.`);
    }
    console.log(`  tag ${tag} pushed at ${shortSha(facts.headSha)}`);
  } else {
    console.log(`  tag ${tag} is already on origin at HEAD — keeping it`);
  }

  if (decision.completed.githubRelease) {
    console.log("  GitHub release is already published with a matching artifact — leaving it untouched");
  } else if (facts.githubRelease && facts.githubRelease.isDraft) {
    withRecovery(
      "asset upload to the existing draft release failed",
      "the tag is pushed but nothing is published. Fix the issue and rerun — the draft release is recognized and its assets replaced.",
      () => run("gh", ["release", "upload", tag, zipPath, "--clobber"])
    );
  } else {
    withRecovery(
      "draft GitHub release creation failed",
      `the tag is pushed but nothing is published. Inspect with \`gh release view ${tag}\` and rerun — a matching draft is reused.`,
      () => run("gh", ["release", "create", tag, "--draft", "--title", `Apple SDK v${version}`, "--notes", notes, zipPath])
    );
  }

  if (args.skipUpload) {
    console.log("• [skip-upload] leaving the GitHub release as a draft — rerun without --skip-upload to upload the CDN artifact and publish");
    return;
  }

  if (decision.completed.cdnObject) {
    console.log("  CDN object already matches this build — skipping upload");
  } else {
    withRecovery(
      "R2 upload failed",
      "the GitHub release is still a draft and nothing is public. Fix credentials or connectivity and rerun — the tag and the draft release are recognized and reused.",
      () => run("npx", ["wrangler", "r2", "object", "put", `${R2_BUCKET}/sdks/apple/${filename}`,
        "--file", zipPath, "--remote", "--content-type", "application/zip"])
    );
    verifyCdnChecksum(filename, artifact.sha256);
  }

  if (facts.githubRelease && !facts.githubRelease.isDraft) {
    console.log("  GitHub release was already published");
  } else {
    withRecovery(
      "publishing the draft release failed",
      `the CDN artifact is uploaded and verified. After checking the ${filename} asset yourself, publish manually with: gh release edit ${tag} --draft=false`,
      () => run("gh", ["release", "edit", tag, "--draft=false"])
    );
  }

  console.log(`\n✓ Apple SDK v${version} successfully released!`);
  console.log("  Next manual steps:");
  console.log(`  - git push origin ${RELEASE_BRANCH}   (publishes the SDK version bump commit)`);
  console.log("  - update the README install snippet if this version becomes the documented one");
}

// Importing this module (as ReleasePreflightTests does) must be side-effect
// free; main() runs only when the script is executed directly.
function isDirectInvocation() {
  if (!process.argv[1]) return false;
  try {
    return realpathSync(process.argv[1]) === realpathSync(fileURLToPath(import.meta.url));
  } catch {
    return false;
  }
}

if (isDirectInvocation()) {
  main().catch((err) => fail(err.stack || err.message));
}
